FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG en_US.UTF-8

RUN apt update && apt install -y \
    build-essential \
    git \
    nano \
    vim \
    wget \
    curl \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    mesa-utils \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update

RUN mkdir -p /root/ros2_ws/src
WORKDIR /root/ros2_ws

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN echo "[ -f /root/ros2_ws/install/setup.bash ] && source /root/ros2_ws/install/setup.bash" >> /root/.bashrc

CMD ["bash"]
